SideMenu & info & homework
GRAM-DSM/GRAMO-iOS pull request #5
Opened 2021-04-27 10:56 UTC by jangseoyoung

2021-04-27 11:23 UTC, MoonJisu requested changes

2021-04-27 11:23 UTC, MoonJisu commented on GRAMO/GRAMO/VC/info/infoListVC.swift
> +var nationalTableView : UITableView!
전역 변수는 사용하지 않는게 좋아요!

2021-04-27 14:17 UTC, Ga-yo requested changes
코드의 흐름은 나쁘지 않은 것 같아요~!

정리하자면
- 중복되는 리뷰는 하지 않았습니다. 하나의 코멘트에 해당되는 리뷰가 다른 코드에도 적용될 수 있으니 전체적으로 확인해주세요!
- 이미 인지하고 있는 부분을 언급한 코멘트에는 답변말고 이모지를 달고 수정하지 않아도 좋아요
- 전체적으로 테스트를 위해 작성한 프린트문은 삭제하고 커밋하면 가독성이 높아질 것 같아요!
- 함수를 활용해서 코드를 간결하게 만들면 좋을 것 같습니다.

2021-04-27 14:17 UTC, Ga-yo commented on GRAMO/GRAMO/VC/homework/homeworkAddVC.swift
>  class homeworkAddVC: UIViewController, UITextViewDelegate {
보통 클래스 이름은 대문자로 시작하는게 좋아요 ! 여러 명명규칙은 [여기](https://google.github.io/swift/)를 참고해보아요

2021-04-27 14:17 UTC, Ga-yo commented on GRAMO/GRAMO/VC/homework/homeworkAssignedVC.swift
> +    @IBOutlet weak var titleTxt: UITextField!
Txt로 줄인 이유가 있을까요??

2021-04-27 14:17 UTC, Ga-yo commented on GRAMO/GRAMO/VC/homework/homeworkListVC.swift
> +            let finalDate2 = enddate.components(separatedBy: ["-", ":"," "])
중복되는 코드는 함수로 만들면 좋을 것 같네요 :)

2021-04-28 00:24 UTC, jangseoyoung commented on GRAMO/GRAMO/Networking/Networking.swift
> +        }
넵

2021-04-28 00:25 UTC, jangseoyoung commented on GRAMO/GRAMO/VC/homework/homeworkAssignedVC.swift
> +    @IBOutlet weak var titleTxt: UITextField!
너무 길어서 줄였는데 다시 되돌려놓도록 하겠습니다

2021-04-28 00:30 UTC, jangseoyoung commented on GRAMO/GRAMO/Networking/Networking.swift
> +        case .getHwContent(let homeworkId):
수정하겠습니다

2021-04-30 05:55 UTC, Ga-yo requested changes
- 코드 정렬이나 포맷에도 신경을 써주세요! (불필요한 개행, 중괄호)
- self는 강한 참조 순환을 일으킬 수 있으니 공부해보는 것도 좋을 것 같아요 :)
- 모든 파일명에서 ViewController를 VC라고 표현했는데 줄이는것 보다 그대로 표현하는걸 추천합니다! 대부분 회사에서도 그대로 표현하고, 변수 사용시에만 vc라고 사용하고 있어요

2021-04-30 05:55 UTC, Ga-yo commented on GRAMO/GRAMO/VC/homework/homeworkAddVC.swift
> +        textViewDidBeginEditing(detailTextView)
이런 delegate 함수는 왜 따로 호출을 해줬나요??

2021-04-30 05:55 UTC, Ga-yo commented on GRAMO/GRAMO/VC/homework/homeworkListVC.swift
> +        let bar:UINavigationBar! =  self.navigationController?.navigationBar
이 함수는 왜 extension에 추가하지 않았나요?

2021-04-30 05:55 UTC, Ga-yo commented on GRAMO/GRAMO/VC/homework/homeworkAssignedVC.swift
> +                    self.titleTextField.text = model.title
self 사용을 줄이는게 좋습니다 ! self로 인해 메모리 누수가 생길 수 있습니다

2021-04-30 05:55 UTC, Ga-yo commented on GRAMO/GRAMO/VC/homework/homeworkAddVC.swift
>                  catch {
정렬이 이상해요!

2021-04-30 05:59 UTC, jangseoyoung commented on GRAMO/GRAMO/VC/homework/homeworkAddVC.swift
> +        textViewDidBeginEditing(detailTextView)
글자수 제한 걸려고요!!

2021-04-30 06:17 UTC, Ga-yo commented on GRAMO/GRAMO/VC/homework/homeworkAddVC.swift
> +        textViewDidBeginEditing(detailTextView)
어 근데 textViewDidBeginEditing는 textView가 수정될 때 호출이 되기 때문에 굳이 호출을 해주지 않아도 됩니다. 다른 delegate의 메소드도 비슷한 경우가 많습니다 delegate에 대해 더 알아보는게 좋을 것 같아요!

2021-04-30 06:21 UTC, jangseoyoung commented on GRAMO/GRAMO/VC/homework/homeworkAssignedVC.swift
> +                    self.titleTextField.text = model.title
오 선배 근데 여기서 self를 빼버리면 오류가 나요 ㅠㅠ

2021-04-30 06:42 UTC, Ga-yo commented on GRAMO/GRAMO/VC/homework/homeworkAssignedVC.swift
> +                    self.titleTextField.text = model.title
그건 ARC에서 캡쳐리스트에 대해 알아보면 해결이 될 것 같아요 self와 ARC는 밀접한 관계가 있어요.! 한번 공부해보는 것도 좋을 것 같아요:)

2021-04-30 07:18 UTC, MoonJisu approved these changes

2021-04-30 07:19 UTC, Ga-yo approved these changes

2021-04-30 07:20 UTC, merged